name: Keepalive

on:
  workflow_dispatch:
  # At 11:50 AM UTC, on day 21 of the month
  schedule:
    - cron: '50 11 21 * *'

jobs:
  keepalive:
    name: Keepalive
    # Only run cron on the silverstripe account
    if: (github.event_name == 'schedule' && github.repository_owner == 'silverstripe') || (github.event_name != 'schedule')
    runs-on: ubuntu-latest
    steps:
      - name: Keepalive
        uses: silverstripe/gha-keepalive@v1
